[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Autoware_msgs from PZJ"
authors = [{name = "PZJ", email = "1751368522@qq.com"}]
dynamic = ["version", "description"]
